development:
  adapter: postgresql
  encoding: unicode
  database: widgetly
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: widgetly_test
  pool: 5
#
# production:
#   <<: *default
#   database: d3h5r40ofqiues
#   username: qnmwiabgxixcmq
#   password: <%= ENV['WIDGETLY_DATABASE_PASSWORD'] %>
